indian_stocks = [
            "20MICRONS.NS - 20 Microns Limited",
"21STCENMGM.NS - 21st Century Management Services Limited",
"3IINFOTECH.NS - 3i Infotech Limited",
"3MINDIA.NS - 3M India Limited",
"3PLAND.NS - 3P Land Holdings Limited",
"5PAISA.NS - 5paisa Capital Limited",
"63MOONS.NS - 63 moons technologies limited",
"A2ZINFRA.NS - A2Z Infra Engineering Limited",
"AAKASH.NS - Aakash Exploration Services Limited",
"AARON.NS - Aaron Industries Limited",
"AARTIDRUGS.NS - Aarti Drugs Limited",
"AARTIIND.NS - Aarti Industries Limited",
"AARVEEDEN.NS - Aarvee Denims & Exports Limited",
"AARVI.NS - Aarvi Encon Limited",
"AAVAS.NS - Aavas Financiers Limited",
"ABAN.NS - Aban Offshore Limited",
"ABB.NS - ABB India Limited",
"ABBOTINDIA.NS - Abbott India Limited",
"ABCAPITAL.NS - Aditya Birla Capital Limited",
"ABFRL.NS - Aditya Birla Fashion and Retail Limited",
"ABMINTLTD.NS - ABM International Limited",
"ABSLAMC.NS - Aditya Birla Sun Life AMC Limited",
"ACC.NS - ACC Limited",
"ACCELYA.NS - Accelya Solutions India Limited",
"ACCURACY.NS - Accuracy Shipping Limited",
"ACE.NS - Action Construction Equipment Limited",
"ADANIENT.NS - Adani Enterprises Limited",
"ADANIGREEN.NS - Adani Green Energy Limited",
"ADANIPORTS.NS - Adani Ports and Special Economic Zone Limited",
"ADANIPOWER.NS - Adani Power Limited",
"ADANITRANS.NS - Adani Energy Solutions Limited",
"ADFFOODS.NS - ADF Foods Limited",
"ADORWELD.NS - Ador Welding Limited",
"ADROITINFO.NS - Adroit Infotech Limited",
"ADSL.NS - Allied Digital Services Limited",
"ADVANIHOTR.NS - Advani Hotels & Resorts (India) Limited",
"ADVENZYMES.NS - Advanced Enzyme Technologies Limited",
"AEGISCHEM.NS - Aegis Logistics Limited",
"AETHER.NS - Aether Industries Limited",
"AFFLE.NS - Affle (India) Limited",
"AGARIND.NS - Agarwal Industrial Corporation Limited",
"AGI.NS - AGI Greenpac Limited",
"AGRITECH.NS - Agri-Tech (India) Limited",
"AGROPHOS.NS - Agro Phos India Limited",
"AHLUCONT.NS - Ahluwalia Contracts (India) Limited",
"AIAENG.NS - AIA Engineering Limited",
"AIRAN.NS - Airan Limited",
"AJANTPHARM.NS - Ajanta Pharma Limited",
"AJMERA.NS - Ajmera Realty & Infra India Limited",
"AKASH.NS - Akash Infra-Projects Limited",
"AKSHARCHEM.NS - AksharChem India Limited",
"AKSHOPTFBR.NS - Aksh Optifibre Limited",
"AKZOINDIA.NS - Akzo Nobel India Limited",
"ALANKIT.NS - Alankit Limited",
"ALBERTDAVD.NS - Albert David Limited",
"ALEMBICLTD.NS - Alembic Limited",
"ALKALI.NS - Alkali Metals Limited",
"ALKEM.NS - Alkem Laboratories Limited",
"ALKYLAMINE.NS - Alkyl Amines Chemicals Limited",
"ALLCARGO.NS - Allcargo Logistics Limited",
"ALLSEC.NS - Allsec Technologies Limited",
"ALOKINDS.NS - Alok Industries Limited",
"ALPA.NS - Alpa Laboratories Limited",
"ALPHAGEO.NS - Alphageo (India) Limited",
"AMARAJABAT.NS - Amara Raja Energy & Mobility Limited",
"AMBER.NS - Amber Enterprises India Limited",
"AMBIKCO.NS - Ambika Cotton Mills Limited",
"AMBUJACEM.NS - Ambuja Cements Limited",
"AMJLAND.NS - Amj Land Holdings Limited",
"AMRUTANJAN.NS - Amrutanjan Health Care Limited",
"ANANDRATHI.NS - Anand Rathi Wealth Limited",
"ANANTRAJ.NS - Anant Raj Limited",
"ANDHRACEMT.NS - Andhra Cements Limited",
"ANDHRAPAP.NS - Andhra Paper Limited",
"ANGELONE.NS - Angel One Limited",
"ANIKINDS.NS - Anik Industries Limited",
"ANKITMETAL.NS - Ankit Metal & Power Limited",
"ANSALAPI.NS - Ansal Properties & Infrastructure Limited",
"APARINDS.NS - Apar Industries Limited",
"APCOTEXIND.NS - Apcotex Industries Limited",
"APEX.NS - Apex Frozen Foods Limited",
"APLAPOLLO.NS - APL Apollo Tubes Limited",
"APOLLOHOSP.NS - Apollo Hospitals Enterprise Limited",
"APOLLOPIPE.NS - Apollo Pipes Limited",
"APOLLOTYRE.NS - Apollo Tyres Limited",
"APOLSINHOT.NS - Apollo Sindoori Hotels Limited",
"APTECHT.NS - Aptech Limited",
"APTUS.NS - Aptus Value Housing Finance India Limited",
"ARCHIDPLY.NS - Archidply Industries Limited",
"ARCHIES.NS - Archies Limited",
"ARE&M.NS - Amara Raja Energy & Mobility Limited",
"ARMANFIN.NS - Arman Financial Services Limited",
"AROMATICA.NS - Aromatica Fragrances & Flavours Limited",
"ARROWGREEN.NS - Arrow Greentech Limited",
"ARSHIYA.NS - Arshiya Limited",
"ARVIND.NS - Arvind Limited",
"ARVINDFASN.NS - Arvind Fashions Limited",
"ASAHIINDIA.NS - Asahi India Glass Limited",
"ASAHISONG.NS - Asahi Songwon Colors Limited",
"ASAL.NS - Automotive Stampings and Assemblies Limited",
"ASHAPURMIN.NS - Ashapura Minechem Limited",
"ASHIANA.NS - Ashiana Housing Limited",
"ASHIMASYN.NS - Ashima Limited",
"ASHOKA.NS - Ashoka Buildcon Limited",
"ASHOKLEY.NS - Ashok Leyland Limited",
"ASIANPAINT.NS - Asian Paints Limited",
"ASIANTILES.NS - Asian Granito India Limited",
"ASTEC.NS - Astec Lifesciences Limited",
"ASTERDM.NS - Aster DM Healthcare Limited",
"ASTRAL.NS - Astral Limited",
"ASTRAMICRO.NS - Astra Microwave Products Limited",
"ASTRAZEN.NS - AstraZeneca Pharma India Limited",
"ATFL.NS - Agro Tech Foods Limited",
"ATL.NS - Allied Timbers Limited",
"ATUL.NS - Atul Limited",
"AUBANK.NS - AU Small Finance Bank Limited",
"AURIONPRO.NS - Aurionpro Solutions Limited",
"AUROPHARMA.NS - Aurobindo Pharma Limited",
"AUTOAXLES.NS - Automotive Axles Limited",
"AUTOIND.NS - Autoline Industries Limited",
"AVADHSUGAR.NS - Avadh Sugar & Energy Limited",
"AVANTIFEED.NS - Avanti Feeds Limited",
"AVTNPL.NS - AVT Natural Products Limited",
"AXISBANK.NS - Axis Bank Limited",
"AXISCADES.NS - AXISCADES Technologies Limited",
"AYMSYNTEX.NS - AYM Syntex Limited",
"BAFNAPH.NS - Bafna Pharmaceuticals Limited",
"BAJAJ-AUTO.NS - Bajaj Auto Limited",
"BAJAJCON.NS - Bajaj Consumer Care Limited",
"BAJAJELEC.NS - Bajaj Electricals Limited",
"BAJAJFINSV.NS - Bajaj Finserv Limited",
"BAJAJHIND.NS - Bajaj Hindusthan Sugar Limited",
"BAJAJHLDNG.NS - Bajaj Holdings & Investment Limited",
"BAJFINANCE.NS - Bajaj Finance Limited",
"BALAJITELE.NS - Balaji Telefilms Limited",
"BALAMINES.NS - Balaji Amines Limited",
"BALKRISIND.NS - Balkrishna Industries Limited",
"BALLARPUR.NS - Ballarpur Industries Limited",
"BALMLAWRIE.NS - Balmer Lawrie & Co. Limited",
"BALRAMCHIN.NS - Balrampur Chini Mills Limited",
"BANARISUG.NS - Bannari Amman Sugars Limited",
"BANCOINDIA.NS - Banco Products (I) Limited",
"BANDHANBNK.NS - Bandhan Bank Limited",
"BANG.NS - Bang Overseas Limited",
"BANKA.NS - Banka BioLoo Limited",
"BANKBARODA.NS - Bank of Baroda",
"BANKINDIA.NS - Bank of India",
"BANSWRAS.NS - Banswara Syntex Limited",
"BARBEQUE.NS - Barbeque-Nation Hospitality Limited",
"BASF.NS - BASF India Limited",
"BATAINDIA.NS - Bata India Limited",
"BAYERCROP.NS - Bayer CropScience Limited",
"BBL.NS - Bharat Bijlee Limited",
"BCG.NS - Brightcom Group Limited",
"BCP.NS - B.C. Power Controls Limited",
"BDL.NS - Bharat Dynamics Limited",
"BEL.NS - Bharat Electronics Limited",
"BEML.NS - BEML Limited",
"BEPL.NS - Bhansali Engineering Polymers Limited",
"BERGEPAINT.NS - Berger Paints India Limited",
"BFINVEST.NS - BF Investment Limited",
"BFUTILITIE.NS - BF Utilities Limited",
"BGLOBAL.NS - BSL Limited",
"BGRENERGY.NS - BGR Energy Systems Limited",
"BHAGERIA.NS - Bhageria Industries Limited",
"BHANDARI.NS - Bhandari Hosiery Exports Limited",
"BHARATFORG.NS - Bharat Forge Limited",
"BHARATGEAR.NS - Bharat Gears Limited",
"BHARATRAS.NS - Bharat Rasayan Limited",
"BHARATWIRE.NS - Bharat Wire Ropes Limited",
"BHARTIARTL.NS - Bharti Airtel Limited",
"BHEL.NS - Bharat Heavy Electricals Limited",
"BIGBLOC.NS - Bigbloc Construction Limited",
"BIKAJI.NS - Bikaji Foods International Limited",
"BIL.NS - Bhartiya International Limited",
"BINDALAGRO.NS - Bindal Agro Chem Limited",
"BIOCON.NS - Biocon Limited",
"BIRLACABLE.NS - Birla Cable Limited",
"BIRLACORPN.NS - Birla Corporation Limited",
"BIRLAMONEY.NS - Aditya Birla Money Limited",
"BLAL.NS - B&A Limited",
"BLISSGVS.NS - Bliss GVS Pharma Limited",
"BLKASHYAP.NS - B. L. Kashyap and Sons Limited",
"BLS.NS - BLS International Services Limited",
"BLUECHIP.NS - Blue Chip India Limited",
"BLUEDART.NS - Blue Dart Express Limited",
"BLUESTARCO.NS - Blue Star Limited",
"BODALCHEM.NS - Bodal Chemicals Limited",
"BOMDYEING.NS - Bombay Dyeing & Mfg Company Limited",
"BORORENEW.NS - Borosil Renewables Limited",
"BOSCHLTD.NS - Bosch Limited",
"BPCL.NS - Bharat Petroleum Corporation Limited",
"BPL.NS - BPL Limited",
"BRIGADE.NS - Brigade Enterprises Limited",
"BRITANNIA.NS - Britannia Industries Limited",
"BRNL.NS - Bharat Road Network Limited",
"BROOKS.NS - Brooks Laboratories Limited",
"BSE.NS - BSE Limited",
"BSL.NS - BSL Limited",
"BSOFT.NS - Birlasoft Limited",
"BURGERKING.NS - Restaurant Brands Asia Limited",
"BUTTERFLY.NS - Butterfly Gandhimathi Appliances Limited",
"BVCL.NS - Barak Valley Cements Limited",
"BYKE.NS - The Byke Hospitality Limited",
"CADILAHC.NS - Zydus Lifesciences Limited",
"CALSOFT.NS - California Software Company Limited",
"CAMLINFINE.NS - Camlin Fine Sciences Limited",
"CAMPUS.NS - Campus Activewear Limited",
"CAMS.NS - Computer Age Management Services Limited",
"CANBK.NS - Canara Bank",
"CANFINHOME.NS - Can Fin Homes Limited",
"CANTABIL.NS - Cantabil Retail India Limited",
"CAPACITE.NS - Capacit'e Infraprojects Limited",
"CAPLIPOINT.NS - Caplin Point Laboratories Limited",
"CARBORUNIV.NS - Carborundum Universal Limited",
"CAREERP.NS - Career Point Limited",
"CARERATING.NS - CARE Ratings Limited",
"CASTROLIND.NS - Castrol India Limited",
"CCL.NS - CCL Products (India) Limited",
"CDSL.NS - Central Depository Services (India) Limited",
"CEATLTD.NS - CEAT Limited",
"CELEBRITY.NS - Celebrity Fashions Limited",
"CENTENKA.NS - Century Enka Limited",
"CENTEXT.NS - Century Extrusions Limited",
"CENTRALBK.NS - Central Bank of India",
"CENTRUM.NS - Centrum Capital Limited",
"CENTUM.NS - Centum Electronics Limited",
"CENTURYPLY.NS - Century Plyboards (India) Limited",
"CERA.NS - Cera Sanitaryware Limited",
"CEREBRAINT.NS - Cerebra Integrated Technologies Limited",
"CESC.NS - CESC Limited",
"CGCL.NS - Capri Global Capital Limited",
"CGPOWER.NS - CG Power and Industrial Solutions Limited",
"CHALET.NS - Chalet Hotels Limited",
"CHAMBLFERT.NS - Chambal Fertilizers & Chemicals Limited",
"CHEMCON.NS - Chemcon Speciality Chemicals Limited",
"CHEMFAB.NS - Chemfab Alkalis Limited",
"CHEMPLASTS.NS - Chemplast Sanmar Limited",
"CHENNPETRO.NS - Chennai Petroleum Corporation Limited",
"CHOLAFIN.NS - Cholamandalam Investment and Finance Company Limited",
"CHOLAHLDNG.NS - Cholamandalam Financial Holdings Limited",
"CIGNITITEC.NS - Cigniti Technologies Limited",
"CINELINE.NS - Cineline India Limited",
"CINEVISTA.NS - Cinevista Limited",
"CIPLA.NS - Cipla Limited",
"CLEAN.NS - Clean Science and Technology Limited",
"CMSINFO.NS - CMS Info Systems Limited",
"COALINDIA.NS - Coal India Limited",
"COCHINSHIP.NS - Cochin Shipyard Limited",
"COFFEEDAY.NS - Coffee Day Enterprises Limited",
"COLPAL.NS - Colgate-Palmolive (India) Limited",
"COMPINFO.NS - Compuage Infocom Limited",
"CONCOR.NS - Container Corporation of India Limited",
"CONFIPET.NS - Confidence Petroleum India Limited",
"CONTROLPR.NS - Control Print Limited",
"COROMANDEL.NS - Coromandel International Limited",
"COSMOFIRST.NS - Cosmo First Limited",
"CRAFTSMAN.NS - Craftsman Automation Limited",
"CREDITACC.NS - CreditAccess Grameen Limited",
"CREST.NS - Crest Ventures Limited",
"CRISIL.NS - CRISIL Limited",
"CROMPTON.NS - Crompton Greaves Consumer Electricals Limited",
"CSBBANK.NS - CSB Bank Limited",
"CUB.NS - City Union Bank Limited",
"CUMMINSIND.NS - Cummins India Limited",
"CUPID.NS - Cupid Limited",
"CYBERMEDIA.NS - Cyber Media (India) Limited",
"CYBERTECH.NS - Cybertech Systems and Software Limited",
"CYIENT.NS - Cyient Limited",
"DABUR.NS - Dabur India Limited",
"DALBHARAT.NS - Dalmia Bharat Limited",
"DALMIASUG.NS - Dalmia Bharat Sugar and Industries Limited",
"DAMODARIND.NS - Damodar Industries Limited",
"DATAMATICS.NS - Datamatics Global Services Limited",
"DATAPATTNS.NS - Data Patterns (India) Limited",
"DBL.NS - Dilip Buildcon Limited",
"DBCORP.NS - D.B.Corp Limited",
"DBREALTY.NS - D B Realty Limited",
"DBSTOCKBRO.NS - DB (International) Stock Brokers Limited",
"DCAL.NS - Dishman Carbogen Amcis Limited",
"DCBBANK.NS - DCB Bank Limited",
"DCM.NS - DCM Limited",
"DCMNVL.NS - DCM NOUVELLE LIMITED",
"DCMSHRIRAM.NS - DCM Shriram Limited",
"DCW.NS - DCW Limited",
"DEEPAKFERT.NS - Deepak Fertilisers and Petrochemicals Corporation Limited",
"DEEPAKNTR.NS - Deepak Nitrite Limited",
"DEEPINDS.NS - Deep Industries Limited",
"DELHIVERY.NS - Delhivery Limited",
"DELTACORP.NS - Delta Corp Limited",
"DEN.NS - Den Networks Limited",
"DEVYANI.NS - Devyani International Limited",
"DFMFOODS.NS - DFM Foods Limited",
"DGCONTENT.NS - Digicontent Limited",
"DHAMPURSUG.NS - Dhampur Sugar Mills Limited",
"DHANBANK.NS - Dhanlaxmi Bank Limited",
"DHANI.NS - Dhani Services Limited",
"DHANUKA.NS - Dhanuka Agritech Limited",
"DIAMONDYD.NS - Prataap Snacks Limited",
"DIAPOWER.NS - Diamond Power Infrastructure Limited",
"DICIND.NS - DIC India Limited",
"DIGISPICE.NS - DiGiSPICE Technologies Limited",
"DISHTV.NS - Dish TV India Limited",
"DIVISLAB.NS - Divi's Laboratories Limited",
"DIXON.NS - Dixon Technologies (India) Limited",
"DLF.NS - DLF Limited",
"DLINKINDIA.NS - D-Link (India) Limited",
"DMART.NS - Avenue Supermarts Limited",
"DODLA.NS - Dodla Dairy Limited",
"DOLAT.NS - Dolat Algotech Limited",
"DOLLAR.NS - Dollar Industries Limited",
"DPL.NS - Dhunseri Petrochem Limited",
"DPSCLTD.NS - DPSC Limited",
"DRCSYSTEMS.NS - DRC Systems India Limited",
"DREDGECORP.NS - Dredging Corporation of India Limited",
"DRREDDY.NS - Dr. Reddy's Laboratories Limited",
"DSSL.NS - Dynacons Systems & Solutions Limited",
"DTIL.NS - Dhunseri Tea & Industries Limited",
"DUCON.NS - Ducon Infratechnologies Limited",
"DWARKESH.NS - Dwarikesh Sugar Industries Limited",
"DYNAMATECH.NS - Dynamatic Technologies Limited",
"E2E.NS - E2E Networks Limited",
"EASEMYTRIP.NS - Easy Trip Planners Limited",
"ECLERX.NS - eClerx Services Limited",
"EDELWEISS.NS - Edelweiss Financial Services Limited",
"EICHERMOT.NS - Eicher Motors Limited",
"EIDPARRY.NS - EID-Parry (India) Limited",
"EIHAHOTELS.NS - EIH Associated Hotels Limited",
"EIHHOTEL.NS - EIH Limited",
"EIMCOELECO.NS - Eimco Elecon (India) Limited",
"EKC.NS - Everest Kanto Cylinder Limited",
"ELECON.NS - Elecon Engineering Company Limited",
"ELECTCAST.NS - Electrosteel Castings Limited",
"ELECTHERM.NS - Electrotherm (India) Limited",
"ELGIEQUIP.NS - Elgi Equipments Limited",
"EMAMILTD.NS - Emami Limited",
"EMAMIPAP.NS - Emami Paper Mills Limited",
"EMAMIREAL.NS - Emami Realty Limited",
"EMKAY.NS - Emkay Global Financial Services Limited",
"ENDURANCE.NS - Endurance Technologies Limited",
"ENERGYDEV.NS - Energy Development Company Limited",
"ENGINERSIN.NS - Engineers India Limited",
"EQUITASBNK.NS - Equitas Small Finance Bank Limited",
"ERIS.NS - Eris Lifesciences Limited",
"EROSMEDIA.NS - Eros International Media Limited",
"ESABINDIA.NS - ESAB India Limited",
"ESCORTS.NS - Escorts Kubota Limited",
"ESSARSHPNG.NS - Essar Shipping Limited",
"ESTER.NS - Ester Industries Limited",
"EVEREADY.NS - Eveready Industries India Limited",
"EVERESTIND.NS - Everest Industries Limited",
"EXIDEIND.NS - Exide Industries Limited",
"EXXARO.NS - Exxaro Tiles Limited",
"FACT.NS - Fertilisers and Chemicals Travancore Limited",
"FAIRCHEM.NS - Fairchem Organics Limited",
"FCL.NS - Fineotex Chemical Limited",
"FCONSUMER.NS - Future Consumer Limited",
"FDC.NS - FDC Limited",
"FEDERALBNK.NS - The Federal Bank Limited",
"FEL.NS - Future Enterprises Limited",
"FELDVR.NS - Future Enterprises Limited - DVR",
"FIEMIND.NS - Fiem Industries Limited",
"FILATEX.NS - Filatex India Limited",
"FINCABLES.NS - Finolex Cables Limited",
"FINEORG.NS - Fine Organic Industries Limited",
"FINPIPE.NS - Finolex Industries Limited",
"FLEXITUFF.NS - Flexituff Ventures International Limited",
"FLFL.NS - Future Lifestyle Fashions Limited",
"FLUOROCHEM.NS - Gujarat Fluorochemicals Limited",
"FMGOETZE.NS - Federal-Mogul Goetze (India) Limited",
"FMNL.NS - Future Market Networks Limited",
"FORCEMOT.NS - Force Motors Limited",
"FORTIS.NS - Fortis Healthcare Limited",
"FOSECOIND.NS - Foseco India Limited",
"FRETAIL.NS - Future Retail Limited",
"FSC.NS - Future Supply Chain Solutions Limited",
"GABRIEL.NS - Gabriel India Limited",
"GAEL.NS - Gujarat Ambuja Exports Limited",
"GAIL.NS - GAIL (India) Limited",
"GALAXYSURF.NS - Galaxy Surfactants Limited",
"GAMMONIND.NS - Gammon India Limited",
"GANDHITUBE.NS - Gandhi Special Tubes Limited",
"GANECOS.NS - Ganesha Ecosphere Limited",
"GANESHBE.NS - Ganesh Benzoplast Limited",
"GANGESSECU.NS - Ganges Securities Limited",
"GATI.NS - Gati Limited",
"GAYAPROJ.NS - Gayatri Projects Limited",
"GEECEE.NS - GeeCee Ventures Limited",
"GEPIL.NS - GE Power India Limited",
"GESHIP.NS - The Great Eastern Shipping Company Limited",
"GET&D.NS - GE T&D India Limited",
"GFLLIMITED.NS - GFL Limited",
"GHCL.NS - GHCL Limited",
"GICHSGFIN.NS - GIC Housing Finance Limited",
"GICRE.NS - General Insurance Corporation of India",
"GILLANDERS.NS - Gillanders Arbuthnot & Co. Limited",
"GILLETTE.NS - Gillette India Limited",
"GINNIFILA.NS - Ginni Filaments Limited",
"GIPCL.NS - Gujarat Industries Power Company Limited",
"GISOLUTION.NS - GI Engineering Solutions Limited",
"GLAND.NS - Gland Pharma Limited",
"GLAXO.NS - GlaxoSmithKline Pharmaceuticals Limited",
"GLENMARK.NS - Glenmark Pharmaceuticals Limited",
"GLOBALVECT.NS - Global Vectra Helicorp Limited",
"GLOBUSSPR.NS - Globus Spirits Limited",
"GMDCLTD.NS - Gujarat Mineral Development Corporation Limited",
"GMRINFRA.NS - GMR Airports Infrastructure Limited",
"GMRPOWER.NS - GMR Power and Urban Infra Limited",
"GNA.NS - GNA Axles Limited",
"GNFC.NS - Gujarat Narmada Valley Fertilizers & Chemicals Limited",
"GOACARBON.NS - Goa Carbon Limited",
"GOCLCORP.NS - GOCL Corporation Limited",
"GODFRYPHLP.NS - Godfrey Phillips India Limited",
"GODREJAGRO.NS - Godrej Agrovet Limited",
"GODREJCP.NS - Godrej Consumer Products Limited",
"GODREJIND.NS - Godrej Industries Limited",
"GODREJPROP.NS - Godrej Properties Limited",
"GOENKA.NS - Goenka Diamond and Jewels Limited",
"GOKEX.NS - Gokaldas Exports Limited",
"GOKUL.NS - Gokul Refoils and Solvent Limited",
"GOKULAGRO.NS - Gokul Agro Resources Limited",
"GOLDENTEAK.NS - Golden Tobacco Limited",
"GOLDIAM.NS - Goldiam International Limited",
"GOLDTECH.NS - Goldstone Technologies Limited",
"GOODLUCK.NS - Goodluck India Limited",
"GPIL.NS - Godawari Power And Ispat limited",
"GPPL.NS - Gujarat Pipavav Port Limited",
"GPTINFRA.NS - GPT Infraprojects Limited",
"GRANULES.NS - Granules India Limited",
"GRAPHITE.NS - Graphite India Limited",
"GRASIM.NS - Grasim Industries Limited",
"GRAVITA.NS - Gravita India Limited",
"GREAVESCOT.NS - Greaves Cotton Limited",
"GREENLAM.NS - Greenlam Industries Limited",
"GREENPANEL.NS - Greenpanel Industries Limited",
"GREENPLY.NS - Greenply Industries Limited",
"GRINDWELL.NS - Grindwell Norton Limited",
"GRINFRA.NS - G R Infraprojects Limited",
"GROBTEA.NS - The Grob Tea Company Limited",
"GRSE.NS - Garden Reach Shipbuilders & Engineers Limited",
"GSFC.NS - Gujarat State Fertilizers & Chemicals Limited",
"GSL.NS - Goa Shipyard Limited",
"GSPL.NS - Gujarat State Petronet Limited",
"GTL.NS - GTL Limited",
"GTLINFRA.NS - GTL Infrastructure Limited",
"GTPL.NS - GTPL Hathway Limited",
"GUJALKALI.NS - Gujarat Alkalies and Chemicals Limited",
"GUJAPOLLO.NS - Gujarat Apollo Industries Limited",
"GUJGASLTD.NS - Gujarat Gas Limited",
"GUJRAFFIA.NS - Gujarat Raffia Industries Limited",
"GULFOILLUB.NS - Gulf Oil Lubricants India Limited",
"GULFPETRO.NS - GP Petroleums Limited",
"GULPOLY.NS - Gulshan Polyols Limited",
"HAL.NS - Hindustan Aeronautics Limited",
"HAPPSTMNDS.NS - Happiest Minds Technologies Limited",
"HARRMALAYA.NS - Harrisons Malayalam Limited",
"HATHWAY.NS - Hathway Cable & Datacom Limited",
"HATSUN.NS - Hatsun Agro Product Limited",
"HAVELLS.NS - Havells India Limited",
"HBLPOWER.NS - HBL Power Systems Limited",
"HBSL.NS - HB Stockholdings Limited",
"HCC.NS - Hindustan Construction Company Limited",
"HCG.NS - Healthcare Global Enterprises Limited",
"HCL-INSYS.NS - HCL Infosystems Limited",
"HCLTECH.NS - HCL Technologies Limited",
"HDFCAMC.NS - HDFC Asset Management Company Limited",
"HDFCBANK.NS - HDFC Bank Limited",
"HDFCLIFE.NS - HDFC Life Insurance Company Limited",
"HDIL.NS - Housing Development and Infrastructure Limited",
"HEG.NS - HEG Limited",
"HEIDELBERG.NS - HeidelbergCement India Limited",
"HERANBA.NS - Heranba Industries Limited",
"HERCULES.NS - Hercules Hoists Limited",
"HERITGFOOD.NS - Heritage Foods Limited",
"HEROMOTOCO.NS - Hero MotoCorp Limited",
"HESTERBIO.NS - Hester Biosciences Limited",
"HEXAWARE.NS - Hexaware Technologies Limited",
"HFCL.NS - HFCL Limited",
"HGINFRA.NS - H.G. Infra Engineering Limited",
"HGS.NS - Hinduja Global Solutions Limited",
"HIKAL.NS - Hikal Limited",
"HIL.NS - HIL Limited",
"HIMATSEIDE.NS - Himatsingka Seide Limited",
"HINDALCO.NS - Hindalco Industries Limited",
"HINDCOMPOS.NS - Hindustan Composites Limited",
"HINDCON.NS - Hindcon Chemicals Limited",
"HINDCOPPER.NS - Hindustan Copper Limited",
"HINDMOTORS.NS - Hindustan Motors Limited",
"HINDNATGLS.NS - Hindusthan National Glass & Industries Limited",
"HINDOILEXP.NS - Hindustan Oil Exploration Company Limited",
"HINDPETRO.NS - Hindustan Petroleum Corporation Limited",
"HINDUNILVR.NS - Hindustan Unilever Limited",
"HINDZINC.NS - Hindustan Zinc Limited",
"HIRECT.NS - Hind Rectifiers Limited",
"HISARMETAL.NS - Hisar Metal Industries Limited",
"HITECH.NS - Hi-Tech Pipes Limited",
"HITECHGEAR.NS - The Hi-Tech Gears Limited",
"HLEGLAS.NS - HLE Glascoat Limited",
"HMT.NS - HMT Limited",
"HMVL.NS - Hindustan Media Ventures Limited",
"HONAUT.NS - Honeywell Automation India Limited",
"HONDAPOWER.NS - Honda India Power Products Limited",
"HUDCO.NS - Housing & Urban Development Corporation Limited",
"HUHTAMAKI.NS - Huhtamaki India Limited",
"IBREALEST.NS - Indiabulls Real Estate Limited",
"IBULHSGFIN.NS - Indiabulls Housing Finance Limited",
"ICICIBANK.NS - ICICI Bank Limited",
"ICICIGI.NS - ICICI Lombard General Insurance Company Limited",
"ICICIPRULI.NS - ICICI Prudential Life Insurance Company Limited",
"ICRA.NS - ICRA Limited",
"IDBI.NS - IDBI Bank Limited",
"IDEA.NS - Vodafone Idea Limited",
"IDFC.NS - IDFC Limited",
"IDFCFIRSTB.NS - IDFC First Bank Limited",
"IEX.NS - Indian Energy Exchange Limited",
"IFBAGRO.NS - IFB Agro Industries Limited",
"IFBIND.NS - IFB Industries Limited",
"IFCI.NS - IFCI Limited",
"IFGLEXPOR.NS - IFGL Refractories Limited",
"IGARASHI.NS - Igarashi Motors India Limited",
"IGL.NS - Indraprastha Gas Limited",
"IGPL.NS - I G Petrochemicals Limited",
"IIFL.NS - IIFL Finance Limited",
"IIFLSEC.NS - IIFL Securities Limited",
"IMFA.NS - Indian Metals & Ferro Alloys Limited",
"IMPAL.NS - India Motor Parts and Accessories Limited",
"INDBANK.NS - Indbank Merchant Banking Services Limited",
"INDHOTEL.NS - The Indian Hotels Company Limited",
"INDIAAMINES.NS - India Glycols Limited",
"INDIACEM.NS - The India Cements Limited",
"INDIAGLYCO.NS - India Glycols Limited",
"INDIAMART.NS - Indiamart Intermesh Limited",
"INDIANB.NS - Indian Bank",
"INDIANCARD.NS - Indian Card Clothing Company Limited",
"INDIANHUME.NS - Indian Hume Pipe Company Limited",
"INDIGO.NS - InterGlobe Aviation Limited",
"INDIGOPNTS.NS - Indigo Paints Limited",
"INDLMETER.NS - IMP Powers Limited",
"INDNIPPON.NS - India Nippon Electricals Limited",
"INDOCO.NS - Indoco Remedies Limited",
"INDORAMA.NS - Indo Rama Synthetics (India) Limited",
"INDOSOLAR.NS - Indosolar Limited",
"INDOSTAR.NS - IndoStar Capital Finance Limited",
"INDOTECH.NS - Indo Tech Transformers Limited",
"INDOTHAI.NS - Indo-Thai Securities Limited",
"INDOWIND.NS - Indowind Energy Limited",
"INDRAMEDCO.NS - Indraprastha Medical Corporation Limited",
"INDSWFTLAB.NS - Indus Fila Limited",
"INDUSINDBK.NS - IndusInd Bank Limited",
"INDUSTOWER.NS - Indus Towers Limited",
"INEOSSTYRO.NS - INEOS Styrolution India Limited",
"INFIBEAM.NS - Infibeam Avenues Limited",
"INFOMEDIA.NS - Infomedia Press Limited",
"INFRATEL.NS - Bharti Infratel Limited",
"INFY.NS - Infosys Limited",
"INGERRAND.NS - Ingersoll Rand (India) Limited",
"INOXGREEN.NS - Inox Green Energy Services Limited",
"INOXWIND.NS - Inox Wind Limited",
"INSECTICID.NS - Insecticides (India) Limited",
"INTELLECT.NS - Intellect Design Arena Limited",
"INTENTECH.NS - Intense Technologies Limited",
"IOB.NS - Indian Overseas Bank",
"IOC.NS - Indian Oil Corporation Limited",
"IOLCP.NS - IOL Chemicals and Pharmaceuticals Limited",
"IPCALAB.NS - Ipca Laboratories Limited",
"IRB.NS - IRB Infrastructure Developers Limited",
"IRCON.NS - Ircon International Limited",
"IRCTC.NS - Indian Railway Catering And Tourism Corporation Limited",
"IRFC.NS - Indian Railway Finance Corporation Limited",
"ISEC.NS - ICICI Securities Limited",
"ISFT.NS - Intrasoft Technologies Limited",
"ISGEC.NS - Isgec Heavy Engineering Limited",
"ISMTLTD.NS - ISMT Limited",
"ITC.NS - ITC Limited",
"ITDC.NS - India Tourism Development Corporation Limited",
"ITDCEM.NS - ITD Cementation India Limited",
"ITI.NS - ITI Limited",
"IVC.NS - IL&FS Investment Managers Limited",
"IVP.NS - IVP Limited",
"IVZINGOLD.NS - Invesco India Gold Exchange Traded Fund",
"IZMO.NS - IZMO Limited",
"J&KBANK.NS - The Jammu & Kashmir Bank Limited",
"JAGRAN.NS - Jagran Prakashan Limited",
"JAGSNPHARM.NS - Jagsonpal Pharmaceuticals Limited",
"JAIBALAJI.NS - Jai Balaji Industries Limited",
"JAICORPLTD.NS - Jai Corp Limited",
"JAINSTUDIO.NS - Jain Studios Limited",
"JALAN.NS - Jalan Transolutions (India) Limited",
"JAMNAAUTO.NS - Jamna Auto Industries Limited",
"JASH.NS - Jash Engineering Limited",
"JAYAGROGN.NS - Jayant Agro-Organics Limited",
"JAYBARMARU.NS - Jay Bharat Maruti Limited",
"JAYNECOIND.NS - Jayaswal Neco Industries Limited",
"JBCHEPHARM.NS - JB Chemicals & Pharmaceuticals Limited",
"JBFIND.NS - JBF Industries Limited",
"JBMA.NS - JBM Auto Limited",
"JCHAC.NS - Johnson Controls-Hitachi Air Conditioning India Limited",
"JETAIRWAYS.NS - Jet Airways (India) Limited",
"JETFREIGHT.NS - Jet Freight Logistics Limited",
"JHS.NS - JHS Svendgaard Laboratories Limited",
"JINDALPHOT.NS - Jindal Photo Limited",
"JINDALPOLY.NS - Jindal Poly Films Limited",
"JINDALSAW.NS - Jindal Saw Limited",
"JINDALSTEL.NS - Jindal Steel & Power Limited",
"JINDRILL.NS - Jindal Drilling & Industries Limited",
"JINDWORLD.NS - Jindal Worldwide Limited",
"JIOFIN.NS - Jio Financial Services Limited",
"JIYAECO.NS - Jiya Eco-Products Limited",
"JKCEMENT.NS - J.K. Cement Limited",
"JKIL.NS - J.Kumar Infraprojects Limited",
"JKLAKSHMI.NS - JK Lakshmi Cement Limited",
"JKPAPER.NS - JK Paper Limited",
"JKTYRE.NS - JK Tyre & Industries Limited",
"JMA.NS - Jullundur Motor Agency (Delhi) Limited",
"JMFINANCIL.NS - JM Financial Limited",
"JOCIL.NS - Jocil Limited",
"JPASSOCIAT.NS - Jaiprakash Associates Limited",
"JPINFRATEC.NS - Jaypee Infratech Limited",
"JPOLYINVST.NS - JPMORGAN INDIAN INVESTMENT TRUST PLC",
"JPPOWER.NS - Jaiprakash Power Ventures Limited",
"JSL.NS - Jindal Stainless Limited",
"JSLHISAR.NS - Jindal Stainless (Hisar) Limited",
"JSWENERGY.NS - JSW Energy Limited",
"JSWHL.NS - JSW Holdings Limited",
"JSWSTEEL.NS - JSW Steel Limited",
"JTEKTINDIA.NS - Jtekt India Limited",
"JUBILANT.NS - Jubilant Pharmova Limited",
"JUBLFOOD.NS - Jubilant FoodWorks Limited",
"JUBLINDS.NS - Jubilant Industries Limited",
"JUBLINGREA.NS - Jubilant Ingrevia Limited",
"JUSTDIAL.NS - Just Dial Limited",
"JWL.NS - Jupiter Wagons Limited",
"JYOTHYLAB.NS - Jyothy Labs Limited",
"JYOTISTRUC.NS - Jyoti Structures Limited",
"KABRAEXTRU.NS - Kabra Extrusiontechnik Limited",
"KAJARIACER.NS - Kajaria Ceramics Limited",
"KAKATCEM.NS - Kakatiya Cement Sugar & Industries Limited",
"KALPATPOWR.NS - Kalpataru Projects International Limited",
"KALYANIKSTL.NS - Kalyani Steels Limited",
"KALYANKJIL.NS - Kalyan Jewellers India Limited",
"KAMATHOTEL.NS - Kamat Hotels (I) Limited",
"KAMDHENU.NS - Kamdhenu Limited",
"KANANIIND.NS - Kanani Industries Limited",
"KANORICHEM.NS - Kanoria Chemicals & Industries Limited",
"KANSAINER.NS - Kansai Nerolac Paints Limited",
"KAPSTON.NS - Kapston Services Limited",
"KARMAENG.NS - Karma Energy Limited",
"KARURVYSYA.NS - Karur Vysya Bank Limited",
"KAVVERITEL.NS - Kavveri Telecom Products Limited",
"KAYA.NS - Kaya Limited",
"KCP.NS - KCP Limited",
"KCPSUGIND.NS - K.C.P. Sugar and Industries Corporation Limited",
"KDDL.NS - KDDL Limited",
"KEC.NS - KEC International Limited",
"KECL.NS - Kirloskar Electric Company Limited",
"KEI.NS - KEI Industries Limited",
"KELLTONTEC.NS - Kellton Tech Solutions Limited",
"KERNEX.NS - Kernex Microsystems (India) Limited",
"KESORAMIND.NS - Kesoram Industries Limited",
"KEYFINSERV.NS - Keynote Financial Services Limited",
"KHADIM.NS - Khadim India Limited",
"KHAITANLTD.NS - Khaitan (India) Limited",
"KHANDSE.NS - Khandwala Securities Limited",
"KICL.NS - Kalyani Investment Company Limited",
"KILITCH.NS - Kilitch Drugs (India) Limited",
"KINGFA.NS - Kingfa Science & Technology (India) Limited",
"KIOCL.NS - KIOCL Limited",
"KIRIINDUS.NS - Kiri Industries Limited",
"KIRLOSBROS.NS - Kirloskar Brothers Limited",
"KIRLOSENG.NS - Kirloskar Oil Engines Limited",
"KIRLOSIND.NS - Kirloskar Industries Limited",
"KITEX.NS - Kitex Garments Limited",
"KKCL.NS - Kewal Kiran Clothing Limited",
"KMSUGAR.NS - K.M. Sugar Mills Limited",
"KNRCON.NS - KNR Constructions Limited",
"KOHINOOR.NS - Kohinoor Foods Limited",
"KOKUYOCMLN.NS - Kokuyo Camlin Limited",
"KOLTEPATIL.NS - Kolte-Patil Developers Limited",
"KOPRAN.NS - Kopran Limited",
"KOTAKBANK.NS - Kotak Mahindra Bank Limited",
"KOTHARIPET.NS - Kothari Petrochemicals Limited",
"KOTHARIPRO.NS - Kothari Products Limited",
"KPIGREEN.NS - KPI Green Energy Limited",
"KPIL.NS - Kalpataru Projects International Limited",
"KPITTECH.NS - KPIT Technologies Limited",
"KPRMILL.NS - K.P.R. Mill Limited",
"KRBL.NS - KRBL Limited",
"KREBSBIO.NS - Krebs Biochemicals & Industries Limited",
"KRIDHANIND.NS - Kridhan Infra Limited",
"KRISHANA.NS - Krishana Phoschem Limited",
"KRISHNA.NS - Krishna Institute of Medical Sciences Limited",
"KSB.NS - KSB Limited",
"KSCL.NS - Kaveri Seed Company Limited",
"KSERASERA.NS - KSS Limited",
"KSL.NS - Kalyani Steels Limited",
"KTKBANK.NS - The Karnataka Bank Limited",
"KUANTUM.NS - Kuantum Papers Limited",
"L&TFH.NS - L&T Finance Holdings Limited",
"LAGNAM.NS - Lagnam Spintex Limited",
"LAKPRE.NS - Lakshmi Precision Screws Limited",
"LAKSHVILAS.NS - Lakshmi Vilas Bank Limited",
"LALPATHLAB.NS - Dr. Lal PathLabs Limited",
"LAMBODHARA.NS - Lambodhara Textiles Limited",
"LAOPALA.NS - La Opala RG Limited",
"LASA.NS - Lasa Supergenerics Limited",
"LATENTVIEW.NS - Latent View Analytics Limited",
"LAURUSLABS.NS - Laurus Labs Limited",
"LAXMICOT.NS - Laxmi Cotspin Limited",
"LAXMIMACH.NS - Lakshmi Machine Works Limited",
"LEMONTREE.NS - Lemon Tree Hotels Limited",
"LFIC.NS - L&T Finance Holdings Limited",
"LGBBROSLTD.NS - L.G.Balakrishnan & Bros.Limited",
"LGBFORGE.NS - LGB Forge Limited",
"LIBAS.NS - Libas Consumer Products Limited",
"LIBERTSHOE.NS - Liberty Shoes Limited",
"LICHSGFIN.NS - LIC Housing Finance Limited",
"LIKHITHA.NS - Likhitha Infrastructure Limited",
"LINCOLN.NS - Lincoln Pharmaceuticals Limited",
"LINDEINDIA.NS - Linde India Limited",
"LTIM.NS - LTIMindtree Limited",
"LTTS.NS - L&T Technology Services Limited",
"LUMAXIND.NS - Lumax Industries Limited",
"LUMAXTECH.NS - Lumax Auto Technologies Limited",
"LUPIN.NS - Lupin Limited",
"LUXIND.NS - Lux Industries Limited",
"LYKALABS.NS - Lyka Labs Limited",
"M&M.NS - Mahindra & Mahindra Limited",
"M&MFIN.NS - Mahindra & Mahindra Financial Services Limited",
"MAANALU.NS - Maan Aluminium Limited",
"MADHAV.NS - Madhav Marbles and Granites Limited",
"MADHUCON.NS - Madhucon Projects Limited",
"MADRASFERT.NS - Madras Fertilizers Limited",
"MAGADHSUGAR.NS - Magadh Sugar & Energy Limited",
"MAGMA.NS - Poonawalla Fincorp Limited",
"MAHABANK.NS - Bank of Maharashtra",
"MAHAPEXLTD.NS - Mahaan Foods Limited",
"MAHASTEEL.NS - Mahamaya Steel Industries Limited",
"MAHESHWARI.NS - Maheshwari Logistics Limited",
"MAHINDCIE.NS - CIE Automotive India Limited",
"MAHLIFE.NS - Mahindra Lifespace Developers Limited",
"MAHLOG.NS - Mahindra Logistics Limited",
"MAHSCOOTER.NS - Maharashtra Scooters Limited",
"MAHSEAMLES.NS - Maharashtra Seamless Limited",
"MAITHANALL.NS - Maithan Alloys Limited",
"MAJESCO.NS - Majesco Limited",
"MALUPAPER.NS - Malu Paper Mills Limited",
"MANAKALU.NS - Manaksia Aluminium Company Limited",
"MANAKCOAT.NS - Manaksia Coated Metals & Industries Limited",
"MANAKSIA.NS - Manaksia Limited",
"MANAKSTEEL.NS - Manaksia Steels Limited",
"MANALIPETC.NS - Manali Petrochemicals Limited",
"MANAPPURAM.NS - Manappuram Finance Limited",
"MANGALAM.NS - Mangalam Cement Limited",
"MANGCHEFER.NS - Mangalore Chemicals & Fertilizers Limited",
"MANGLMCEM.NS - Mangalam Cement Limited",
"MANINDS.NS - Man Industries (India) Limited",
"MANINFRA.NS - Man Infraconstruction Limited",
"MANKIND.NS - Mankind Pharma Limited",
"MANORAMA.NS - Manorama Industries Limited",
"MANUGRAPH.NS - Manugraph India Limited",
"MAPMYINDIA.NS - C.E. Info Systems Limited",
"MARALOVER.NS - Maral Overseas Limited",
"MARATHON.NS - Marathon Nextgen Realty Limited",
"MARICO.NS - Marico Limited",
"MARKSANS.NS - Marksans Pharma Limited",
"MARUTI.NS - Maruti Suzuki India Limited",
"MASFIN.NS - MAS Financial Services Limited",
"MASTEK.NS - Mastek Limited",
"MATRIMONY.NS - Matrimony.com Limited",
"MAWANASUG.NS - Mawana Sugars Limited",
"MAXESTATES.NS - Max Estates Limited",
"MAXHEALTH.NS - Max Healthcare Institute Limited",
"MAXIND.NS - Max India Limited",
"MAXVIL.NS - Max Ventures and Industries Limited",
"MAYURUNIQ.NS - Mayur Uniquoters Limited",
"MAZDA.NS - Mazda Limited",
"MAZDOCK.NS - Mazagon Dock Shipbuilders Limited",
"MBAPL.NS - Madhya Bharat Agro Products Limited",
"MBECL.NS - McNally Bharat Engineering Company Limited",
"MBLINFRA.NS - MBL Infrastructures Limited",
"MCDOWELL-N.NS - United Spirits Limited",
"MCLEODRUSS.NS - McLeod Russel India Limited",
"MCX.NS - Multi Commodity Exchange of India Limited",
"MEDICAMEQ.NS - Medicamen Biotech Limited",
"MEDPLUS.NS - Medplus Health Services Limited",
"MEGH.NS - Meghmani Organics Limited",
"MELSTAR.NS - Melstar Information Technologies Limited",
"MENONBE.NS - Menon Bearings Limited",
"MEP.NS - MEP Infrastructure Developers Limited",
"METROBRAND.NS - Metro Brands Limited",
"METROPOLIS.NS - Metropolis Healthcare Limited",
"MFSL.NS - Max Financial Services Limited",
"MGL.NS - Mahanagar Gas Limited",
"MHRIL.NS - Mahindra Holidays & Resorts India Limited",
"MIDHANI.NS - Mishra Dhatu Nigam Limited",
"MINDACORP.NS - Minda Corporation Limited",
"MINDAIND.NS - Uno Minda Limited",
"MINDTECK.NS - Mindteck (India) Limited",
"MIRCELECTR.NS - MIRC Electronics Limited",
"MIRZAINT.NS - Redtape Limited",
"MMFL.NS - MM Forgings Limited",
"MMP.NS - MMP Industries Limited",
"MMTC.NS - MMTC Limited",
"MODIRUBBER.NS - Modi Rubber Limited",
"MODISNME.NS - Modern Insulators Limited",
"MOHITIND.NS - Mohit Industries Limited",
"MOIL.NS - MOIL Limited",
"MOLDTECH.NS - Mold-Tek Technologies Limited",
"MOLDTKPAC.NS - Mold-Tek Packaging Limited",
"MONARCH.NS - Monarch Networth Capital Limited",
"MONTECARLO.NS - Monte Carlo Fashions Limited",
"MOREPENLAB.NS - Morepen Laboratories Limited",
"MOTHERSON.NS - Samvardhana Motherson International Limited",
"MOTILALOFS.NS - Motilal Oswal Financial Services Limited",
"MOTOGENFIN.NS - The Motor & General Finance Limited",
"MPHASIS.NS - MphasiS Limited",
"MPSLTD.NS - MPS Limited",
"MRF.NS - MRF Limited",
"MRPL.NS - Mangalore Refinery and Petrochemicals Limited",
"MSPL.NS - MSP Steel & Power Limited",
"MSTCLTD.NS - Mstc Limited",
"MTNL.NS - Mahanagar Telephone Nigam Limited",
"MUTHOOTCAP.NS - Muthoot Capital Services Limited",
"MUTHOOTFIN.NS - Muthoot Finance Limited",
"MVL.NS - MVL Limited",
"NACLIND.NS - NACL Industries Limited",
"NAGAFERT.NS - Nagarjuna Fertilizers and Chemicals Limited",
"NAGREEKCAP.NS - Nagreeka Capital & Infrastructure Limited",
"NAGREEKEXP.NS - Nagreeka Exports Limited",
"NAHARCAP.NS - Nahar Capital and Financial Services Limited",
"NAHARINDUS.NS - Nahar Industrial Enterprises Limited",
"NAHARPOLY.NS - Nahar Poly Films Limited",
"NAHARSPING.NS - Nahar Spinning Mills Limited",
"NAM-INDIA.NS - Nippon Life India Asset Management Limited",
"NATCOPHARM.NS - Natco Pharma Limited",
"NATHBIOGEN.NS - Nath Bio-Genes (India) Limited",
"NATIONALUM.NS - National Aluminium Company Limited",
"NAUKRI.NS - Info Edge (India) Limited",
"NAVINFLUOR.NS - Navin Fluorine International Limited",
"NAZARA.NS - Nazara Technologies Limited",
"NBCC.NS - NBCC (India) Limited",
"NBVENTURES.NS - NAVA LIMITED",
"NCC.NS - NCC Limited",
"NCLIND.NS - NCL Industries Limited",
"NDL.NS - Nandan Denim Limited",
"NDTV.NS - New Delhi Television Limited",
"NECLIFE.NS - Nectar Lifesciences Limited",
"NELCAST.NS - Nelcast Limited",
"NELCO.NS - Nelco Limited",
"NEOGEN.NS - Neogen Chemicals Limited",
"NESCO.NS - Nesco Limited",
"NESTLEIND.NS - Nestle India Limited",
"NETWORK18.NS - Network18 Media & Investments Limited",
"NEULANDLAB.NS - Neuland Laboratories Limited",
"NEWGEN.NS - Newgen Software Technologies Limited",
"NEXTMEDIA.NS - Next Mediaworks Limited",
"NFL.NS - National Fertilizers Limited",
"NH.NS - Narayana Hrudayalaya Limited",
"NHPC.NS - NHPC Limited",
"NIACL.NS - The New India Assurance Company Limited",
"NIITLTD.NS - NIIT Limited",
"NILAINFRA.NS - Nila Infrastructures Limited",
"NILKAMAL.NS - Nilkamal Limited",
"NINSYS.NS - NINtec Systems Limited",
"NITINSPIN.NS - Nitin Spinners Limited",
"NITIRAJ.NS - Nitiraj Engineers Limited",
"NKIND.NS - NK Industries Limited",
"NLCINDIA.NS - NLC India Limited",
"NMDC.NS - NMDC Limited",
"NOCIL.NS - Nocil Limited",
"NOIDATOLL.NS - Noida Toll Bridge Company Limited",
"NORBTEAEXP.NS - Norben Tea & Exports Limited",
"NRAIL.NS - N R Agarwal Industries Limited",
"NRBBEARING.NS - NRB Bearing Limited",
"NSIL.NS - NALWA SONS INVESTMENTS LIMITED",
"NTPC.NS - NTPC Limited",
"NUCLEUS.NS - Nucleus Software Exports Limited",
"NYKAA.NS - FSN E-Commerce Ventures Limited",
"OAL.NS - Oriental Aromatics Limited",
"OBEROIRLTY.NS - Oberoi Realty Limited",
"OCCL.NS - Oriental Carbon & Chemicals Limited",
"OFSS.NS - Oracle Financial Services Software Limited",
"OIL.NS - Oil India Limited",
"OLECTRA.NS - Olectra Greentech Limited",
"OMAXE.NS - Omaxe Limited",
"OMINFRA.NS - Omfurn India Limited",
"OMKARCHEM.NS - Omkar Speciality Chemicals Limited",
"ONELIFECAP.NS - Onelife Capital Advisors Limited",
"ONEPOINT.NS - One Point One Solutions Limited",
"ONGC.NS - Oil & Natural Gas Corporation Limited",
"ONMOBILE.NS - OnMobile Global Limited",
"ONWARDTEC.NS - Onward Technologies Limited",
"OPTIEMUS.NS - Optiemus Infracom Limited",
"OPTOCIRCUI.NS - Opto Circuits (India) Limited",
"ORBTEXP.NS - Orbit Exports Limited",
"ORCHPHARMA.NS - Orchid Pharma Limited",
"ORICONENT.NS - Oricon Enterprises Limited",
"ORIENTALTL.NS - Oriental Trimex Limited",
"ORIENTBELL.NS - Orient Bell Limited",
"ORIENTCEM.NS - Orient Cement Limited",
"ORIENTELEC.NS - Orient Electric Limited",
"ORIENTHOT.NS - Oriental Hotels Limited",
"ORIENTPPR.NS - Orient Paper & Industries Limited",
"ORISSAMINE.NS - The Orissa Minerals Development Company Limited",
"OSWALAGRO.NS - Oswal Agro Mills Limited",
"PAEL.NS - PAE Limited",
"PAGEIND.NS - Page Industries Limited",
"PAISALO.NS - Paisalo Digital Limited",
"PALASHSECU.NS - Palash Securities Limited",
"PALREDTEC.NS - Palred Technologies Limited",
"PANACEABIO.NS - Panacea Biotec Limited",
"PANACHE.NS - Panache Digilife Limited",
"PANAMAPET.NS - Panama Petrochem Limited",
"PARACABLES.NS - Paramount Communications Limited",
"PARADEEP.NS - Paradeep Phosphates Limited",
"PARAGMILK.NS - Parag Milk Foods Limited",
"PARAS.NS - Paras Defence and Space Technologies Limited",
"PARSVNATH.NS - Parsvnath Developers Limited",
"PATELENG.NS - Patel Engineering Limited",
"PATINTLOG.NS - Patel Integrated Logistics Limited",
"PAYTM.NS - One 97 Communications Limited",
"PCJEWELLER.NS - PC Jeweller Limited",
"PDMJEPAPER.NS - Pudumjee Paper Products Limited",
"PDSMFL.NS - PDS Limited",
"PEARLPOLY.NS - Pearl Polymers Limited",
"PEL.NS - Piramal Enterprises Limited",
"PENIND.NS - Pennar Industries Limited",
"PENINLAND.NS - Peninsula Land Limited",
"PERSISTENT.NS - Persistent Systems Limited",
"PETRONET.NS - Petronet LNG Limited",
"PFC.NS - Power Finance Corporation Limited",
"PFIZER.NS - Pfizer Limited",
"PFOCUS.NS - Prime Focus Limited",
"PFS.NS - PTC India Financial Services Limited",
"PGEL.NS - PG Electroplast Limited",
"PGHH.NS - Procter & Gamble Hygiene and Health Care Limited",
"PGHL.NS - Procter & Gamble Health Limited",
"PGIL.NS - Pearl Global Industries Limited",
"PHILIPCARB.NS - Phillips Carbon Black Limited",
"PHOENIXLTD.NS - The Phoenix Mills Limited",
"PIDILITIND.NS - Pidilite Industries Limited",
"PIIND.NS - PI Industries Limited",
"PILANIINVS.NS - Pilani Investment and Industries Corporation Limited",
"PILITA.NS - Pil Italica Lifestyle Limited",
"PIONDIST.NS - Pioneer Distilleries Limited",
"PIONEEREMB.NS - Pioneer Embroideries Limited",
"PITTIENG.NS - Pitti Engineering Limited",
"PKTEA.NS - The Peria Karamalai Tea & Produce Company Limited",
"PLASTIBLEN.NS - Plastiblends India Limited",
"PNB.NS - Punjab National Bank",
"PNBGILTS.NS - PNB Gilts Limited",
"PNBHOUSING.NS - PNB Housing Finance Limited",
"PNCINFRA.NS - PNC Infratech Limited",
"PODDARHOUS.NS - Poddar Housing and Development Limited",
"PODDARMENT.NS - Poddar Pigments Limited",
"POKARNA.NS - Pokarna Limited",
"POLICYBZR.NS - PB Fintech Limited",
"POLYCAB.NS - Polycab India Limited",
"POLYMED.NS - Poly Medicure Limited",
"POLYPLEX.NS - Polyplex Corporation Limited",
"PONNIERODE.NS - Ponni Sugars (Erode) Limited",
"POWERGRID.NS - Power Grid Corporation of India Limited",
"POWERINDIA.NS - ABB Power Products and Systems India Limited",
"POWERMECH.NS - Power Mech Projects Limited",
"PPAP.NS - PPAP Automotive Limited",
"PPL.NS - Prakash Pipes Limited",
"PRAENG.NS - Prajay Engineers Syndicate Limited",
"PRAJIND.NS - Praj Industries Limited",
"PRAKASH.NS - Prakash Industries Limited",
"PRAXIS.NS - Praxis Home Retail Limited",
"PRECAM.NS - Precision Camshafts Limited",
"PRECOT.NS - Precot Limited",
"PRECWIRE.NS - Precision Wires India Limited",
"PREMEXPLN.NS - Premier Explosives Limited",
"PREMIER.NS - Premier Limited",
"PREMIERPOL.NS - Premier Polyfilm Limited",
"PRESSMN.NS - Pressman Advertising Limited",
"PRESTIGE.NS - Prestige Estates Projects Limited",
"PRICOLLTD.NS - Pricol Limited",
"PRIMESECU.NS - Prime Securities Limited",
"PRINCEPIPE.NS - Prince Pipes and Fittings Limited",
"PRIVISCL.NS - Privi Speciality Chemicals Limited",
"PROZONER.NS - Prozone Intu Properties Limited",
"PRSMJOHNSN.NS - Prism Johnson Limited",
"PSB.NS - Punjab & Sind Bank",
"PSPPROJECT.NS - PSP Projects Limited",
"PTC.NS - PTC India Limited",
"PTL.NS - PTL Enterprises Limited",
"PUNJABCHEM.NS - Punjab Chemicals & Crop Protection Limited",
"PUNJLLOYD.NS - Punj Lloyd Limited",
"PURVA.NS - Puravankara Limited",
"PVR.NS - PVR INOX Limited",
"PVRINOX.NS - PVR INOX Limited",
"QUESS.NS - Quess Corp Limited",
"QUICKHEAL.NS - Quick Heal Technologies Limited",
"RADAAN.NS - Radaan Mediaworks India Limited",
"RADICO.NS - Radico Khaitan Limited",
"RADIOCITY.NS - Music Broadcast Limited",
"RAILTEL.NS - RailTel Corporation of India Limited",
"RAIN.NS - Rain Industries Limited",
"RAJESHEXPO.NS - Rajesh Exports Limited",
"RAJGLOWIR.NS - Rajnandini Metal Limited",
"RAJRILTD.NS - Raj Rayon Industries Limited",
"RAJSREESUG.NS - Rajshree Sugars & Chemicals Limited",
"RAJTV.NS - Raj Television Network Limited",
"RALLIS.NS - Rallis India Limited",
"RAMANEWS.NS - Shree Rama Newsprint Limited",
"RAMASTEEL.NS - Rama Steel Tubes Limited",
"RAMCOCEM.NS - The Ramco Cements Limited",
"RAMCOIND.NS - Ramco Industries Limited",
"RAMCOSYS.NS - Ramco Systems Limited",
"RAMKY.NS - Ramky Infrastructure Limited",
"RANASUG.NS - Rana Sugars Limited",
"RANEENGINE.NS - Rane Engine Valve Limited",
"RANEHOLDIN.NS - Rane Holdings Limited",
"RATNAMANI.NS - Ratnamani Metals & Tubes Limited",
"RAYMOND.NS - Raymond Limited",
"RBL.NS - Rane Brake Lining Limited",
"RBLBANK.NS - RBL Bank Limited",
"RCF.NS - Rashtriya Chemicals & Fertilizers Limited",
"RCOM.NS - Reliance Communications Limited",
"RECLTD.NS - REC Limited",
"REDINGTON.NS - Redington Limited",
"REFEX.NS - Refex Industries Limited",
"RELAXO.NS - Relaxo Footwears Limited",
"RELCAPITAL.NS - Reliance Capital Limited",
"RELIANCE.NS - Reliance Industries Limited",
"RELIGARE.NS - Religare Enterprises Limited",
"RELINFRA.NS - Reliance Infrastructure Limited",
"RENUKA.NS - Shree Renuka Sugars Limited",
"REPCOHOME.NS - Repco Home Finance Limited",
"REPRO.NS - Repro India Limited",
"RESPONIND.NS - Responsive Industries Limited",
"REVATHI.NS - Revathi Equipment Limited",
"RGL.NS - Renaissance Global Limited",
"RHIM.NS - RHI Magnesita India Limited",
"RICOAUTO.NS - Rico Auto Industries Limited",
"RIIL.NS - Reliance Industrial Infrastructure Limited",
"RITES.NS - RITES Limited",
"RKDL.NS - Ravi Kumar Distilleries Limited",
"RKFORGE.NS - Ramkrishna Forgings Limited",
"RMCL.NS - Radha Madhav Corporation Limited",
"RML.NS - Rane (Madras) Limited",
"RNAVAL.NS - Reliance Naval and Engineering Limited",
"ROHLTD.NS - Royal Orchid Hotels Limited",
"ROLLT.NS - Rollatainers Limited",
"ROLTA.NS - Rolta India Limited",
"ROML.NS - Raj Oil Mills Limited",
"ROSSARI.NS - Rossari Biotech Limited",
"ROSSELLIND.NS - Rossell India Limited",
"ROUTE.NS - Route Mobile Limited",
"RPGLIFE.NS - RPG Life Sciences Limited",
"RPOWER.NS - Reliance Power Limited",
"RPPINFRA.NS - RPP Infra Projects Limited",
"RSSOFTWARE.NS - R. S. Software (India) Limited",
"RSWM.NS - RSWM Limited",
"RSYSTEMS.NS - R Systems International Limited",
"RTNINDIA.NS - Rattanindia Enterprises Limited",
"RTNPOWER.NS - Rattanindia Power Limited",
"RUBYMILLS.NS - The Ruby Mills Limited",
"RUCHI.NS - Ruchi Soya Industries Limited",
"RUCHINFRA.NS - Ruchi Infrastructure Limited",
"RUCHIRA.NS - Ruchira Papers Limited",
"RUPA.NS - Rupa & Company Limited",
"RUSHIL.NS - Rushil Decor Limited",
"RVNL.NS - Rail Vikas Nigam Limited",
"S&SPOWER.NS - S&S Power Switchgear Limited",
"SADBHAV.NS - Sadbhav Engineering Limited",
"SADBHIN.NS - Sadbhav Infrastructure Project Limited",
"SAFARI.NS - Safari Industries (India) Limited",
"SAGARDEEP.NS - Sagardeep Alloys Limited",
"SAGCEM.NS - Sagar Cements Limited",
"SAIL.NS - Steel Authority of India Limited",
"SAKHTISUG.NS - Sakthi Sugars Limited",
"SAKSOFT.NS - Saksoft Limited",
"SAKUMA.NS - Sakuma Exports Limited",
"SALASAR.NS - Salasar Techno Engineering Limited",
"SALONA.NS - Salona Cotspin Limited",
"SALSTEEL.NS - S.A.L. Steel Limited",
"SALZERELEC.NS - Salzer Electronics Limited",
"SAMBHAAV.NS - Sambhaav Media Limited",
"SANCO.NS - Sanco Industries Limited",
"SANDESH.NS - The Sandesh Limited",
"SANDHAR.NS - Sandhar Technologies Limited",
"SANGAMIND.NS - Sangam (India) Limited",
"SANGHIIND.NS - Sanghi Industries Limited",
"SANGHVIMOV.NS - Sanghvi Movers Limited",
"SANOFI.NS - Sanofi India Limited",
"SANWARIA.NS - Sanwaria Consumer Limited",
"SAPPHIRE.NS - Sapphire Foods India Limited",
"SAREGAMA.NS - Saregama India Limited",
"SARLAPOLY.NS - Sarla Performance Fibers Limited",
"SASKEN.NS - Sasken Technologies Limited",
"SASTASUNDR.NS - Sastasundar Ventures Limited",
"SATIA.NS - Satia Industries Limited",
"SATIN.NS - Satin Creditcare Network Limited",
"SBICARD.NS - SBI Cards and Payment Services Limited",
"SBILIFE.NS - SBI Life Insurance Company Limited",
"SBIN.NS - State Bank of India",
"SCAPDVR.NS - Stampede Capital Limited",
"SCHAEFFLER.NS - Schaeffler India Limited",
"SCHAND.NS - S Chand And Company Limited",
"SCHNEIDER.NS - Schneider Electric Infrastructure Limited",
"SCI.NS - Shipping Corporation Of India Limited",
"SDBL.NS - Som Distilleries & Breweries Limited",
"SEAMECLTD.NS - Seamec Limited",
"SELAN.NS - Selan Exploration Technology Limited",
"SEPC.NS - SEPC Limited",
"SEQUENT.NS - Sequent Scientific Limited",
"SESHAPAPER.NS - Seshasayee Paper and Boards Limited",
"SETCO.NS - Setco Automotive Limited",
"SETUINFRA.NS - Setubandhan Infrastructure Limited",
"SEYAIND.NS - Seya Industries Limited",
"SFL.NS - Sheela Foam Limited",
"SGB.NS - Sovereign Gold Bond",
"SGL.NS - STL Global Limited",
"SHAHALLOYS.NS - Shah Alloys Limited",
"SHAKTIPUMP.NS - Shakti Pumps (India) Limited",
"SHALBY.NS - Shalby Limited",
"SHALPAINTS.NS - Shalimar Paints Limited",
"SHANKARA.NS - Shankara Building Products Limited",
"SHANTIGEAR.NS - Shanthi Gears Limited",
"SHARDACROP.NS - Sharda Cropchem Limited",
"SHARDAMOTR.NS - Sharda Motor Industries Limited",
"SHEMAROO.NS - Shemaroo Entertainment Limited",
"SHILPAMED.NS - Shilpa Medicare Limited",
"SHIVAMAUTO.NS - Shivam Autotech Limited",
"SHIVAMILLS.NS - Shiva Mills Limited",
"SHIVATEX.NS - Shiva Texyarn Limited",
"SHK.NS - S H Kelkar and Company Limited",
"SHOPERSTOP.NS - Shoppers Stop Limited",
"SHREDIGCEM.NS - Shree Digvijay Cement Co.Ltd",
"SHREECEM.NS - Shree Cement Limited",
"SHREEPUSHK.NS - Shree Pushkar Chemicals & Fertilisers Limited",
"SHREERAMA.NS - Shree Rama Multi-Tech Limited",
"SHRENIK.NS - Shrenik Limited",
"SHREYANIND.NS - Shreyans Industries Limited",
"SHREYAS.NS - Shreyas Shipping & Logistics Limited",
"SHRIPISTON.NS - Shriram Pistons & Rings Limited",
"SHRIRAMFIN.NS - Shriram Finance Limited",
"SHYAMCENT.NS - Shyam Century Ferrous Limited",
"SHYAMMETL.NS - Shyam Metalics and Energy Limited",
"SIEMENS.NS - Siemens Limited",
"SIGIND.NS - Signet Industries Limited",
"SIL.NS - Standard Industries Limited",
"SILINV.NS - SIL Investments Limited",
"SILLYMONKS.NS - Silly Monks Entertainment Limited",
"SIMBHALS.NS - Simbhaoli Sugars Limited",
"SIMPLEXINF.NS - Simplex Infrastructures Limited",
"SINTEX.NS - Sintex Industries Limited",
"SIRCA.NS - Sirca Paints India Limited",
"SIS.NS - SIS Limited",
"SITINET.NS - Siti Networks Limited",
"SIYSIL.NS - Siyaram Silk Mills Limited",
"SJVN.NS - SJVN Limited",
"SKFINDIA.NS - SKF India Limited",
"SKIL.NS - SKIL Infrastructure Limited",
"SKIPPER.NS - Skipper Limited",
"SKMEGGPROD.NS - SKM Egg Products Export (India) Limited",
"SMARTLINK.NS - Smartlink Holdings Limited",
"SMCGLOBAL.NS - SMC Global Securities Limited",
"SMLISUZU.NS - SML Isuzu Limited",
"SNOWMAN.NS - Snowman Logistics Limited",
"SOBHA.NS - Sobha Limited",
"SOLARA.NS - Solara Active Pharma Sciences Limited",
"SOLARINDS.NS - Solar Industries India Limited",
"SOMANYCERA.NS - Somany Ceramics Limited",
"SOMATEX.NS - Soma Textiles & Industries Limited",
"SONACOMS.NS - Sona BLW Precision Forgings Limited",
"SONATSOFTW.NS - Sonata Software Limited",
"SOTL.NS - Savita Oil Technologies Limited",
"SOUTHBANK.NS - The South Indian Bank Limited",
"SOUTHWEST.NS - South West Pinnacle Exploration Limited",
"SPAL.NS - S.P. Apparels Limited",
"SPANDANA.NS - Spandana Sphoorty Financial Limited",
"SPARC.NS - Sun Pharma Advanced Research Company Limited",
"SPCENET.NS - Spacenet Enterprises India Limited",
"SPECIALITY.NS - Speciality Restaurants Limited",
"SPENCERS.NS - Spencer's Retail Limited",
"SPIC.NS - Southern Petrochemical Industries Corporation Limited",
"SPICEJET.NS - SpiceJet Limited",
"SPLIL.NS - SPL Industries Limited",
"SREINFRA.NS - Srei Infrastructure Finance Limited",
"SRF.NS - SRF Limited",
"SRHHYPOLTD.NS - Sree Rayalaseema Hi-Strength Hypo Limited",
"SRIPIPES.NS - Srikalahasthi Pipes Limited",
"SRTRANSFIN.NS - Shriram Transport Finance Company Limited",
"SSWL.NS - Steel Strips Wheels Limited",
"STAR.NS - Strides Pharma Science Limited",
"STARCEMENT.NS - Star Cement Limited",
"STARPAPER.NS - Star Paper Mills Limited",
"STCINDIA.NS - The State Trading Corporation of India Limited",
"STEELCITY.NS - Steel City Securities Limited",
"STEELXIND.NS - Steel Exchange India Limited",
"STEL.NS - Stel Holdings Limited",
"STERTOOLS.NS - Sterling Tools Limited",
"STLTECH.NS - Sterlite Technologies Limited",
"STOVEKRAFT.NS - Stove Kraft Limited",
"SUBEX.NS - Subex Limited",
"SUBROS.NS - Subros Limited",
"SUDARSCHEM.NS - Sudarshan Chemical Industries Limited",
"SUMEETINDS.NS - Sumeet Industries Limited",
"SUMICHEM.NS - Sumitomo Chemical India Limited",
"SUMIT.NS - Sumit Woods Limited",
"SUNCLAYLTD.NS - Sundaram-Clayton Limited",
"SUNDARAM.NS - Sundaram Multi Pap Limited",
"SUNDARMFIN.NS - Sundaram Finance Limited",
"SUNDARMHLD.NS - Sundaram Finance Holdings Limited",
"SUNDRMBRAK.NS - Sundaram Brake Linings Limited",
"SUNDRMFAST.NS - Sundram Fasteners Limited",
"SUNFLAG.NS - Sunflag Iron and Steel Company Limited",
"SUNPHARMA.NS - Sun Pharmaceutical Industries Limited",
"SUNTECK.NS - Sunteck Realty Limited",
"SUNTV.NS - Sun TV Network Limited",
"SUPERHOUSE.NS - Superhouse Limited",
"SUPERSPIN.NS - Super Spinning Mills Limited",
"SUPRAJIT.NS - Suprajit Engineering Limited",
"SUPREMEIND.NS - The Supreme Industries Limited",
"SUPREMEINF.NS - Supreme Infrastructure India Limited",
"SUPREMEPET.NS - Supreme Petrochem Limited",
"SURANASOL.NS - Surana Solar Limited",
"SURANAT&P.NS - Surana Telecom and Power Limited",
"SURYALAXMI.NS - Suryalakshmi Cotton Mills Limited",
"SURYAROSNI.NS - Surya Roshni Limited",
"SURYODAY.NS - Suryoday Small Finance Bank Limited",
"SUTLEJTEX.NS - Sutlej Textiles and Industries Limited",
"SUVEN.NS - Suven Life Sciences Limited",
"SUVENPHAR.NS - Suven Pharmaceuticals Limited",
"SUZLON.NS - Suzlon Energy Limited",
"SWANENERGY.NS - Swan Energy Limited",
"SWARAJENG.NS - Swaraj Engines Limited",
"SWSOLAR.NS - Sterling and Wilson Renewable Energy Limited",
"SYMPHONY.NS - Symphony Limited",
"SYNCOM.NS - Syncom Formulations (India) Limited",
"SYNGENE.NS - Syngene International Limited",
"TAINWALCHM.NS - Tainwala Chemical and Plastic (I) Limited",
"TAJGVK.NS - Taj GVK Hotels & Resorts Limited",
"TAKE.NS - TAKE Solutions Limited",
"TALBROAUTO.NS - Talbros Automotive Components Limited",
"TANFACIND.NS - Tamilnadu Petroproducts Limited",
"TANLA.NS - Tanla Platforms Limited",
"TANTIACONS.NS - Tantia Constructions Limited",
"TARC.NS - TARC Limited",
"TASTYBITE.NS - Tasty Bite Eatables Limited",
"TATACHEM.NS - Tata Chemicals Limited",
"TATACOFFEE.NS - Tata Coffee Limited",
"TATACOMM.NS - Tata Communications Limited",
"TATACONSUM.NS - Tata Consumer Products Limited",
"TATAELXSI.NS - Tata Elxsi Limited",
"TATAINVEST.NS - Tata Investment Corporation Limited",
"TATAMETALI.NS - Tata Metaliks Limited",
"TATAMOTORS.NS - Tata Motors Limited",
"TATAMTRDVR.NS - Tata Motors Limited - DVR",
"TATAPOWER.NS - The Tata Power Company Limited",
"TATASTEEL.NS - Tata Steel Limited",
"TATASTLBSL.NS - Tata Steel BSL Limited",
"TATASTLLP.NS - Tata Steel Long Products Limited",
"TATATECH.NS - Tata Technologies Limited",
"TCI.NS - Transport Corporation of India Limited",
"TCIDEVELOP.NS - TCI Developers Limited",
"TCIEXP.NS - TCI Express Limited",
"TCIFINANCE.NS - TCI Finance Limited",
"TCNSBRANDS.NS - TCNS Clothing Co. Limited",
"TCPLPACK.NS - TCPL Packaging Limited",
"TCS.NS - Tata Consultancy Services Limited",
"TDPOWERSYS.NS - TD Power Systems Limited",
"TEAMLEASE.NS - TeamLease Services Limited",
"TECHIN.NS - Techindia Nirman Limited",
"TECHM.NS - Tech Mahindra Limited",
"TECHNOE.NS - Techno Electric & Engineering Company Limited",
"TEJASNET.NS - Tejas Networks Limited",
"TERASOFT.NS - Tera Software Limited",
"TEXINFRA.NS - Texmaco Infrastructure & Holdings Limited",
"TEXMOPIPES.NS - Texmo Pipes and Products Limited",
"TEXRAIL.NS - Texmaco Rail & Engineering Limited",
"TFCILTD.NS - Tourism Finance Corporation of India Limited",
"TFL.NS - Transwarranty Finance Limited",
"TGBHOTELS.NS - TGB Banquets And Hotels Limited",
"THANGAMAYL.NS - Thangamayil Jewellery Limited",
"THEINVEST.NS - The Investment Trust Of India Limited",
"THEMISMED.NS - Themis Medicare Limited",
"THERMAX.NS - Thermax Limited",
"THOMASCOOK.NS - Thomas Cook (India) Limited",
"THOMASCOTT.NS - Thomas Scott (India) Limited",
"THYROCARE.NS - Thyrocare Technologies Limited",
"TI.NS - Tilaknagar Industries Limited",
"TIDEWATER.NS - Tide Water Oil Co. (India) Limited",
"TIIL.NS - Technocraft Industries (India) Limited",
"TIINDIA.NS - Tube Investments of India Limited",
"TIMETECHNO.NS - Time Technoplast Limited",
"TIMKEN.NS - Timken India Limited",
"TINPLATE.NS - The Tinplate Company of India Limited",
"TIPSINDLTD.NS - TIPS Industries Limited",
"TIRUMALCHM.NS - Thirumalai Chemicals Limited",
"TITAN.NS - Titan Company Limited",
"TNPETRO.NS - Tamilnadu Petroproducts Limited",
"TNPL.NS - Tamil Nadu Newsprint and Papers Limited",
"TORNTPHARM.NS - Torrent Pharmaceuticals Limited",
"TORNTPOWER.NS - Torrent Power Limited",
"TPLPLASTEH.NS - TPL Plastech Limited",
"TREEHOUSE.NS - Tree House Education & Accessories Limited",
"TRENT.NS - Trent Limited",
"TRF.NS - TRF Limited",
"TRIDENT.NS - Trident Limited",
"TRIGYN.NS - Trigyn Technologies Limited",
"TRIL.NS - Transformers and Rectifiers (India) Limited",
"TRITURBINE.NS - Triveni Turbine Limited",
"TRIVENI.NS - Triveni Engineering & Industries Limited",
"TTKHLTCARE.NS - TTK Healthcare Limited",
"TTKPRESTIG.NS - TTK Prestige Limited",
"TTL.NS - T T Limited",
"TTML.NS - Tata Teleservices (Maharashtra) Limited",
"TV18BRDCST.NS - TV18 Broadcast Limited",
"TVSELECT.NS - TVS Electronics Limited",
"TVSMOTOR.NS - TVS Motor Company Limited",
"TVSSRICHAK.NS - TVS Srichakra Limited",
"TVTODAY.NS - TV Today Network Limited",
"UBL.NS - United Breweries Limited",
"UCALFUEL.NS - Ucal Fuel Systems Limited",
"UCOBANK.NS - UCO Bank",
"UFLEX.NS - Uflex Limited",
"UFO.NS - UFO Moviez India Limited",
"UGARSUGAR.NS - The Ugar Sugar Works Limited",
"UJAAS.NS - Ujaas Energy Limited",
"UJJIVAN.NS - Ujjivan Financial Services Limited",
"UJJIVANSFB.NS - Ujjivan Small Finance Bank Limited",
"ULTRACEMCO.NS - UltraTech Cement Limited",
"UMANGDAIRY.NS - Umang Dairies Limited",
"UNICHEMLAB.NS - Unichem Laboratories Limited",
"UNIDT.NS - United Drilling Tools Limited",
"UNIONBANK.NS - Union Bank of India",
"UNIPARTS.NS - Uniparts India Limited",
"UNITECH.NS - Unitech Limited",
"UNITEDTEA.NS - The United Nilgiri Tea Estates Company Limited",
"UNITY.NS - Unity Infraprojects Limited",
"UNIVARTS.NS - Universal Arts Limited",
"UNIVCABLES.NS - Universal Cables Limited",
"UNIVPHOTO.NS - Universus Photo Imagings Limited",
"UPL.NS - UPL Limited",
"URJA.NS - Urja Global Limited",
"USHAMART.NS - Usha Martin Limited",
"UTIAMC.NS - UTI Asset Management Company Limited",
"UTTAMSUGAR.NS - Uttam Sugar Mills Limited",
"V2RETAIL.NS - V2 Retail Limited",
"VADILALIND.NS - Vadilal Industries Limited",
"VAIBHAVGBL.NS - Vaibhav Global Limited",
"VAISHALI.NS - Vaishali Pharma Limited",
"VAKRANGEE.NS - Vakrangee Limited",
"VALIANTORG.NS - Valiant Organics Limited",
"VARDHACRLC.NS - Vardhman Acrylics Limited",
"VARDHMAN.NS - Vardhman Special Steels Limited",
"VARDHPOLY.NS - Vardhman Polytex Limited",
"VARROC.NS - Varroc Engineering Limited",
"VASCONEQ.NS - Vascon Engineers Limited",
"VASWANI.NS - Vaswani Industries Limited",
"VBL.NS - Varun Beverages Limited",
"VEDL.NS - Vedanta Limited",
"VENKEYS.NS - Venky's (India) Limited",
"VENUSPIPES.NS - Venus Pipes & Tubes Limited",
"VENUSREM.NS - Venus Remedies Limited",
"VERTOZ.NS - Vertoz Advertising Limited",
"VESUVIUS.NS - Vesuvius India Limited",
"VETO.NS - Veto Switchgears and Cables Limited",
"VGUARD.NS - V-Guard Industries Limited",
"VICEROY.NS - Viceroy Hotels Limited",
"VIDHIING.NS - Vidhi Specialty Food Ingredients Limited",
"VIJIFIN.NS - Viji Finance Limited",
"VIKASECO.NS - Vikas Ecotech Limited",
"VIKASLIFE.NS - Vikas Lifecare Limited",
"VIKASPROP.NS - Vikas Proppant & Granite Limited",
"VIMTALABS.NS - Vimta Labs Limited",
"VINATIORGA.NS - Vinati Organics Limited",
"VINDHYATEL.NS - Vindhya Telelinks Limited",
"VINYLINDIA.NS - Vinyl Chemicals (India) Limited",
"VIPCLOTHNG.NS - VIP Clothing Limited",
"VIPIND.NS - VIP Industries Limited",
"VIPULLTD.NS - Vipul Limited",
"VISAKAIND.NS - Visaka Industries Limited",
    "VISASTEEL.NS - Visa Steel Limited",
    "VISHAL.NS - Vishal Fabrics Limited",
    "VISHNU.NS - Vishnu Chemicals Limited",
    "VISHWARAJ.NS - Vishwaraj Sugar Industries Limited",
    "VIVIMEDLAB.NS - Vivimed Labs Limited",
    "VLSFINANCE.NS - VLS Finance Limited",
    "VMART.NS - V-Mart Retail Limited",
    "VOLTAMP.NS - Voltamp Transformers Limited",
    "VOLTAS.NS - Voltas Limited",
    "VRLLOG.NS - VRL Logistics Limited",
    "VSSL.NS - Vardhman Special Steels Limited",
    "VSTIND.NS - VST Industries Limited",
    "VSTTILLERS.NS - V.S.T. Tillers Tractors Limited",
    "VTL.NS - Vardhman Textiles Limited",
    "WABAG.NS - VA Tech Wabag Limited",
    "WABCOINDIA.NS - WABCO India Limited",
    "WALCHANNAG.NS - Walchandnagar Industries Limited",
    "WANBURY.NS - Wanbury Limited",
    "WATERBASE.NS - Waterbase Limited",
    "WEBELSOLAR.NS - Websol Energy System Limited",
    "WEIZMANIND.NS - Weizmann Limited",
    "WELCORP.NS - Welspun Corp Limited",
    "WELENT.NS - Welspun Enterprises Limited",
    "WELINV.NS - Welspun Investments and Commercials Limited",
    "WELSPUNIND.NS - Welspun Living Limited",
    "WENDT.NS - Wendt (India) Limited",
    "WESTLIFE.NS - Westlife Foodworld Limited",
    "WHEELS.NS - Wheels India Limited",
    "WHIRLPOOL.NS - Whirlpool of India Limited",
    "WILLAMAGOR.NS - Williamson Magor & Company Limited",
    "WINDLAS.NS - Windlas Biotech Limited",
    "WIPRO.NS - Wipro Limited",
    "WOCKPHARMA.NS - Wockhardt Limited",
    "WONDERLA.NS - Wonderla Holidays Limited",
    "WSTCSTPAPR.NS - West Coast Paper Mills Limited",
    "XCHANGING.NS - Xchanging Solutions Limited",
    "XELPMOC.NS - Xelpmoc Design and Tech Limited",
    "XPROINDIA.NS - Xpro India Limited",
    "YESBANK.NS - Yes Bank Limited",
    "ZEEL.NS - Zee Entertainment Enterprises Limited",
    "ZEELEARN.NS - Zee Learn Limited",
    "ZEEMEDIA.NS - Zee Media Corporation Limited",
    "ZENITHSTL.NS - Zenith Steel Pipes & Industries Limited",
    "ZENSARTECH.NS - Zensar Technologies Limited",
    "ZENTEC.NS - Zen Technologies Limited",
    "ZFCVINDIA.NS - ZF Commercial Vehicle Control Systems India Limited",
    "ZICOM.NS - Zicom Electronic Security Systems Limited",
    "ZIMLAB.NS - Zim Laboratories Limited",
    "ZODIACCLOTH.NS - Zodiac Clothing Company Limited",
    "ZODJRDMKJ.NS - Zodiac-JRD-MKJ Limited",
    "ZOMATO.NS - Zomato Limited",
    "ZOTA.NS - Zota Health Care Limited",
    "ZUARI.NS - Zuari Agro Chemicals Limited",
    "ZUARIGLOB.NS - Zuari Global Limited",
    "ZYDUSWELL.NS - Zydus Wellness Limited",
        ]